title: Letters from a maladroit
tag_text: Letters from a maladroit
markdown: kramdown
permalink: none
google_analytics: G-57X7ELGV1Y
date_format: '%B %d, %Y'
defaults:
  -
    scope:
      path: ""
    values:
      show_date: true
plugins:
  - jekyll-feed
