title: Letters from a maladroit
tag_text: Letters from a maladroit
markdown: kramdown
permalink: none
google_analytics: UA-58675809-1
date_format: '%B %d, %Y'
defaults:
  -
    scope:
      path: ""
    values:
      show_date: true
